# Generated by Django 5.1.2 on 2024-10-30 20:24

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('registration_date', models.DateField()),
                ('registration_expiration', models.DateField()),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=150)),
                ('street', models.CharField(max_length=150)),
                ('personal_id_number', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('add_to_whatsapp', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Collector Data',
                'verbose_name_plural': 'Collector Data',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('first_name'), models.OrderBy(django.db.models.functions.text.Lower('last_name'), descending=True), name='first_last_name_unique')],
            },
        ),
    ]
