# Generated by Django 5.1.2 on 2024-11-13 01:29

import collector.utils.date_utils
import collector.validators.validators
import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CollectorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=32)),
                ("last_name", models.CharField(max_length=32)),
                (
                    "entry_date",
                    models.DateField(default=collector.utils.date_utils.date_today),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        default=collector.utils.date_utils.one_year_end_of_month
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Expired", "Expired"),
                            ("Removed", "Removed"),
                        ],
                        default="Active",
                        max_length=10,
                    ),
                ),
                ("birth_date", models.DateField()),
                ("place_of_birth", models.CharField(max_length=64)),
                ("address", models.CharField(max_length=64)),
                ("place_of_residence", models.CharField(max_length=32)),
                ("postal_code", models.CharField(max_length=10)),
                (
                    "personal_number",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d+$", "Personal number must contain only digits."
                            ),
                            collector.validators.validators.EqualLengthValidator(
                                11, "Personal number must be exactly 11 digits."
                            ),
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("whatsapp", models.BooleanField(default=True)),
                ("print_card", models.BooleanField(default=False)),
                ("reminder_count", models.PositiveIntegerField(default=0)),
                ("note", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Collector Data",
                "verbose_name_plural": "Collector Data",
                "db_table_comment": "Collector Data",
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("first_name"),
                        models.OrderBy(
                            django.db.models.functions.text.Lower("last_name"),
                            descending=True,
                        ),
                        name="first_last_name_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ExpiringSoonCollectorData",
            fields=[],
            options={
                "verbose_name": "Expiring Soon Collector",
                "verbose_name_plural": "Expiring Soon Collectors",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("collector.collectordata",),
        ),
    ]
