# Generated by Django 5.1.2 on 2024-11-03 16:32

import collector.utils.date_utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collector", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="collectordata",
            table_comment="Collector Data",
        ),
        migrations.RenameField(
            model_name="collectordata",
            old_name="birthdate",
            new_name="birth_date",
        ),
        migrations.RenameField(
            model_name="collectordata",
            old_name="add_to_whatsapp",
            new_name="whatsapp",
        ),
        migrations.RemoveField(
            model_name="collectordata",
            name="number",
        ),
        migrations.RemoveField(
            model_name="collectordata",
            name="registration_date",
        ),
        migrations.AddField(
            model_name="collectordata",
            name="entry_date",
            field=models.DateField(default=collector.utils.date_utils.date_today),
        ),
        migrations.AddField(
            model_name="collectordata",
            name="reminder_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="collectordata",
            name="address",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="collectordata",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="collectordata",
            name="first_name",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="collectordata",
            name="last_name",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="collectordata",
            name="note",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="collectordata",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="collectordata",
            name="place_of_birth",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="collectordata",
            name="place_of_residence",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="collectordata",
            name="postal_code",
            field=models.CharField(max_length=10),
        ),
    ]
