# Generated by Django 5.1.2 on 2024-11-12 20:10

import collector.validators.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collector", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectordata",
            name="personal_number",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d+$", "Personal number must contain only digits."
                    ),
                    collector.validators.validators.EqualLengthValidator(
                        11, "Personal number must be exactly 11 digits."
                    ),
                ],
            ),
        ),
    ]
