# Generated by Django 5.1.2 on 2024-10-31 21:13

import collector.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectordata',
            name='registration_expiration',
            field=models.DateField(default=collector.models.CollectorData.one_year_from_now),
        ),
    ]
