# Generated by Django 5.1.2 on 2024-11-02 21:22

import collector.utils.date_utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collector", "0002_rename_add_to_whatsapp_collectordata_whatsapp_and_more"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="collectordata",
            table_comment="Collector Data",
        ),
        migrations.RenameField(
            model_name="collectordata",
            old_name="birthdate",
            new_name="birth_date",
        ),
        migrations.RemoveField(
            model_name="collectordata",
            name="number",
        ),
        migrations.AlterField(
            model_name="collectordata",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="collectordata",
            name="entry_date",
            field=models.DateField(default=collector.utils.date_utils.date_today),
        ),
    ]
